apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-10-23T11:14:22Z"
  generation: 1
  labels:
    app: demo-deploy
  name: demo-deploy
  namespace: web
  resourceVersion: "228884"
  uid: edd5e0a0-e517-4351-b71f-830d8be90461
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-deploy
    spec:
      containers:
      - image: testdocker4545/my-node-app
        imagePullPolicy: IfNotPresent
        name: k8s-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
