name: CI-CD Docker
on:
push:
branches: [ develop ]

jobs:
build-and-deploy:
runs-on: ubuntu-22.04


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Login to DockerHub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKERHUB_USER }}
password: ${{ secrets.DOCKERHUB_TOKEN }}


- name: Build and push Docker image
uses: docker/build-push-action@v4
with:
context: ./docker
push: true
tags: ${{ secrets.DOCKERHUB_USER }}/k8s-demo:latest


- name: Azure login
uses: azure/login@v1
with:
creds: ${{ secrets.AZURE_CREDENTIALS }}


- name: Set AKS context
uses: azure/aks-set-context@v3
with:
resource-group: demo-aks-rg
cluster-name: demo-aks-cluster


- name: Deploy to AKS
run: |
kubectl apply -f k8s/namespace.yaml
kubectl apply -f k8s/deployment.yaml
kubectl apply -f k8s/service.yaml
